controller_list:
  - name: /arm_controller
    default: true
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: /gripper_controller
    default: true
    action_ns: gripper_action
    type: GripperCommand
    joints:
      - r_gripper_r_joint
      - r_gripper_l_finger_joint
      - r_gripper_motor_screw_joint
      - r_gripper_motor_slider_joint
      - r_gripper_r_finger_joint
